//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandcampDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BandcampDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ….
        /// </summary>
        internal static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse for folder.
        /// </summary>
        internal static string buttonBrowse_ToolTip {
            get {
                return ResourceManager.GetString("buttonBrowse_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check no_w.
        /// </summary>
        internal static string buttonCheckForUpdates {
            get {
                return ResourceManager.GetString("buttonCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download new version.
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Settings.
        /// </summary>
        internal static string buttonOpenSettingsWindow {
            get {
                return ResourceManager.GetString("buttonOpenSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings.
        /// </summary>
        internal static string buttonOpenSettingsWindow_ToolTip {
            get {
                return ResourceManager.GetString("buttonOpenSettingsWindow_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset settings to defaults.
        /// </summary>
        internal static string buttonResetSettings_ToolTip {
            get {
                return ResourceManager.GetString("buttonResetSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        internal static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        internal static string buttonViewChangelog {
            get {
                return ResourceManager.GetString("buttonViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not download changelog from {0}.
        /// </summary>
        internal static string changelogDownloadError {
            get {
                return ResourceManager.GetString("changelogDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for _updates at startup.
        /// </summary>
        internal static string checkBoxCheckForUpdates {
            get {
                return ResourceManager.GetString("checkBoxCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queries the following address when starting the app:.
        /// </summary>
        internal static string checkBoxCheckForUpdates_ToolTip_Part {
            get {
                return ResourceManager.GetString("checkBoxCheckForUpdates_ToolTip_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to _JPG.
        /// </summary>
        internal static string checkBoxCoverArtInFolderConvertToJpg {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderConvertToJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converts cover art to JPG with a compression of 90 (excellent trade-off between size and quality)..
        /// </summary>
        internal static string checkBoxCoverArtInFolderConvertToJpg_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderConvertToJpg_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constrain _maximum width/height.
        /// </summary>
        internal static string checkBoxCoverArtInFolderResize {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resizes cover art to specified max width/height..
        /// </summary>
        internal static string checkBoxCoverArtInFolderResize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderResize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to JP_G.
        /// </summary>
        internal static string checkBoxCoverArtInTagsConvertToJpg {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsConvertToJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converts cover art to JPG with a compression of 90 (excellent trade-off between size and quality)..
        /// </summary>
        internal static string checkBoxCoverArtInTagsConvertToJpg_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsConvertToJpg_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constrain m_aximum width/height.
        /// </summary>
        internal static string checkBoxCoverArtInTagsResize {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resizes cover art to specified max width/height..
        /// </summary>
        internal static string checkBoxCoverArtInTagsResize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsResize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create _playlist for each album.
        /// </summary>
        internal static string checkBoxCreatePlaylist {
            get {
                return ResourceManager.GetString("checkBoxCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creates an album track file for each downloaded album..
        /// </summary>
        internal static string checkBoxCreatePlaylist_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCreatePlaylist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download _artist discography.
        /// </summary>
        internal static string checkBoxDownloadDiscography {
            get {
                return ResourceManager.GetString("checkBoxDownloadDiscography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloads the whole artist discography..
        /// </summary>
        internal static string checkBoxDownloadDiscography_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxDownloadDiscography_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play _notifications sounds.
        /// </summary>
        internal static string checkBoxEnableApplicationSounds {
            get {
                return ResourceManager.GetString("checkBoxEnableApplicationSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification sound for finished downloads..
        /// </summary>
        internal static string checkBoxEnableApplicationSounds_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxEnableApplicationSounds_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use _extended format (only for M3U).
        /// </summary>
        internal static string checkBoxM3uExtended {
            get {
                return ResourceManager.GetString("checkBoxM3uExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M3U playlists in extended format (directives prefaced by the # character)..
        /// </summary>
        internal static string checkBoxM3uExtended_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxM3uExtended_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Modify tracks tags (ID3).
        /// </summary>
        internal static string checkBoxModifyTags {
            get {
                return ResourceManager.GetString("checkBoxModifyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modifies each tag as specified below.
        ///
        ///If not, all tags are unchanged, equivalent to setting &quot;Do not modify&quot; for each tag..
        /// </summary>
        internal static string checkBoxModifyTags_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxModifyTags_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download one album at a time.
        /// </summary>
        internal static string checkBoxOneAlbumAtATime {
            get {
                return ResourceManager.GetString("checkBoxOneAlbumAtATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloads only one album at a time.
        ///If not, all albums are downloaded concurrently (better provided high bandwidth is available)..
        /// </summary>
        internal static string checkBoxOneAlbumAtATime_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxOneAlbumAtATime_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieve _file size before downloading tracks.
        /// </summary>
        internal static string checkBoxRetrieveFilesSize {
            get {
                return ResourceManager.GetString("checkBoxRetrieveFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieves file size to show precise progress.
        ///If not, some bandwidth/time is saved..
        /// </summary>
        internal static string checkBoxRetrieveFilesSize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxRetrieveFilesSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save in _folder.
        /// </summary>
        internal static string checkBoxSaveCoverArtInFolder {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloads cover art to the album folder..
        /// </summary>
        internal static string checkBoxSaveCoverArtInFolder_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save in _tags.
        /// </summary>
        internal static string checkBoxSaveCoverArtInTags {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saves cover art in the track tags..
        /// </summary>
        internal static string checkBoxSaveCoverArtInTags_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInTags_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use HTTP instead of HTTPS.
        /// </summary>
        internal static string checkBoxUseHttpInsteadOfHttps {
            get {
                return ResourceManager.GetString("checkBoxUseHttpInsteadOfHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use this option if your HTTPS traffic to Bandcamp is blocked..
        /// </summary>
        internal static string checkBoxUseHttpInsteadOfHttps_Tooltip {
            get {
                return ResourceManager.GetString("checkBoxUseHttpInsteadOfHttps_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show _verbose log.
        /// </summary>
        internal static string checkBoxVerboseLog {
            get {
                return ResourceManager.GetString("checkBoxVerboseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shows more info in the log..
        /// </summary>
        internal static string checkBoxVerboseLog_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxVerboseLog_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select folder to save albums in.
        /// </summary>
        internal static string folderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("folderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change these settings at your own risk..
        /// </summary>
        internal static string labelAdvancedSettingsWarning {
            get {
                return ResourceManager.GetString("labelAdvancedSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Album art_ist.
        /// </summary>
        internal static string labelAlbumArtist {
            get {
                return ResourceManager.GetString("labelAlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Album _name.
        /// </summary>
        internal static string labelAlbumTitle {
            get {
                return ResourceManager.GetString("labelAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allowed file size _difference (%).
        /// </summary>
        internal static string labelAllowedFileSizeDifference {
            get {
                return ResourceManager.GetString("labelAllowedFileSizeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Artist.
        /// </summary>
        internal static string labelArtist {
            get {
                return ResourceManager.GetString("labelArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reset settings.
        /// </summary>
        internal static string labelButtonResetSettings {
            get {
                return ResourceManager.GetString("labelButtonResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changelog.
        /// </summary>
        internal static string labelChangelog {
            get {
                return ResourceManager.GetString("labelChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changelog.
        /// </summary>
        internal static string labelChangelogTitle {
            get {
                return ResourceManager.GetString("labelChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comm_ents.
        /// </summary>
        internal static string labelComments {
            get {
                return ResourceManager.GetString("labelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File_name format.
        /// </summary>
        internal static string labelCoverArtFileNameFormat {
            get {
                return ResourceManager.GetString("labelCoverArtFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max size (_px).
        /// </summary>
        internal static string labelCoverArtInFolderMaxSize {
            get {
                return ResourceManager.GetString("labelCoverArtInFolderMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max size (p_x).
        /// </summary>
        internal static string labelCoverArtInTagsMaxSize {
            get {
                return ResourceManager.GetString("labelCoverArtInTagsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current version:.
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Max download attempts.
        /// </summary>
        internal static string labelDownloadMaxTries {
            get {
                return ResourceManager.GetString("labelDownloadMaxTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry c_ooldown (sec).
        /// </summary>
        internal static string labelDownloadRetryCooldown {
            get {
                return ResourceManager.GetString("labelDownloadRetryCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry _exponent.
        /// </summary>
        internal static string labelDownloadRetryExponent {
            get {
                return ResourceManager.GetString("labelDownloadRetryExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save albums _to.
        /// </summary>
        internal static string labelDownloadsPath {
            get {
                return ResourceManager.GetString("labelDownloadsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Filename format:.
        /// </summary>
        internal static string labelFileNameFormat {
            get {
                return ResourceManager.GetString("labelFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _HTTP(S) proxy.
        /// </summary>
        internal static string labelHttp {
            get {
                return ResourceManager.GetString("labelHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Port.
        /// </summary>
        internal static string labelHttpPort {
            get {
                return ResourceManager.GetString("labelHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report a bug.
        /// </summary>
        internal static string labelIssues {
            get {
                return ResourceManager.GetString("labelIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Language.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string labelListBoxItemAbout {
            get {
                return ResourceManager.GetString("labelListBoxItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced settings.
        /// </summary>
        internal static string labelListBoxItemAdvanced {
            get {
                return ResourceManager.GetString("labelListBoxItemAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cover art.
        /// </summary>
        internal static string labelListBoxItemCoverArt {
            get {
                return ResourceManager.GetString("labelListBoxItemCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloads.
        /// </summary>
        internal static string labelListBoxItemDownloads {
            get {
                return ResourceManager.GetString("labelListBoxItemDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        internal static string labelListBoxItemGeneral {
            get {
                return ResourceManager.GetString("labelListBoxItemGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network.
        /// </summary>
        internal static string labelListBoxItemNetwork {
            get {
                return ResourceManager.GetString("labelListBoxItemNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist.
        /// </summary>
        internal static string labelListBoxItemPlaylist {
            get {
                return ResourceManager.GetString("labelListBoxItemPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Naming and tags.
        /// </summary>
        internal static string labelListBoxItemTags {
            get {
                return ResourceManager.GetString("labelListBoxItemTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string labelLogin {
            get {
                return ResourceManager.GetString("labelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Lyrics.
        /// </summary>
        internal static string labelLyrics {
            get {
                return ResourceManager.GetString("labelLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File_name format.
        /// </summary>
        internal static string labelPlaylistFileNameFormat {
            get {
                return ResourceManager.GetString("labelPlaylistFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist _format.
        /// </summary>
        internal static string labelPlaylistFormat {
            get {
                return ResourceManager.GetString("labelPlaylistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy.
        /// </summary>
        internal static string labelProxy {
            get {
                return ResourceManager.GetString("labelProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some settings cannot be changed while tracks are downloading..
        /// </summary>
        internal static string labelSettingsInfo {
            get {
                return ResourceManager.GetString("labelSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Theme.
        /// </summary>
        internal static string labelTheme {
            get {
                return ResourceManager.GetString("labelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Track n_umber.
        /// </summary>
        internal static string labelTrackNumber {
            get {
                return ResourceManager.GetString("labelTrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Title.
        /// </summary>
        internal static string labelTrackTitle {
            get {
                return ResourceManager.GetString("labelTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (the log file is always verbose).
        /// </summary>
        internal static string labelVerboseLogInfo {
            get {
                return ResourceManager.GetString("labelVerboseLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string labelVersion {
            get {
                return ResourceManager.GetString("labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not check for updates.
        /// </summary>
        internal static string labelVersionError {
            get {
                return ResourceManager.GetString("labelVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version available.
        /// </summary>
        internal static string labelVersionNewUpdateAvailable {
            get {
                return ResourceManager.GetString("labelVersionNewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Website.
        /// </summary>
        internal static string labelWebsite {
            get {
                return ResourceManager.GetString("labelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Website (Original).
        /// </summary>
        internal static string labelWebsiteOrigin {
            get {
                return ResourceManager.GetString("labelWebsiteOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Album release _year.
        /// </summary>
        internal static string labelYear {
            get {
                return ResourceManager.GetString("labelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel.
        /// </summary>
        internal static string messageBoxButtonCancel {
            get {
                return ResourceManager.GetString("messageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _No.
        /// </summary>
        internal static string messageBoxButtonNo {
            get {
                return ResourceManager.GetString("messageBoxButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _OK.
        /// </summary>
        internal static string messageBoxButtonOK {
            get {
                return ResourceManager.GetString("messageBoxButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Yes.
        /// </summary>
        internal static string messageBoxButtonYes {
            get {
                return ResourceManager.GetString("messageBoxButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel all downloads?.
        /// </summary>
        internal static string messageBoxCancelDownloadsText {
            get {
                return ResourceManager.GetString("messageBoxCancelDownloadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while checking for updates. Please retry later..
        /// </summary>
        internal static string messageBoxCheckForUpdatesError {
            get {
                return ResourceManager.GetString("messageBoxCheckForUpdatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close application.
        /// </summary>
        internal static string messageBoxCloseWindowWhenDownloadingButtonOk {
            get {
                return ResourceManager.GetString("messageBoxCloseWindowWhenDownloadingButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are currently active downloads. Are you sure you want to close the application and stop all downloads?.
        /// </summary>
        internal static string messageBoxCloseWindowWhenDownloadingText {
            get {
                return ResourceManager.GetString("messageBoxCloseWindowWhenDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not open the following link:
        ///{0}.
        /// </summary>
        internal static string messageBoxCouldNotOpenUrlError {
            get {
                return ResourceManager.GetString("messageBoxCouldNotOpenUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You already have the latest version ({0})..
        /// </summary>
        internal static string messageBoxNoUpdateAvailable {
            get {
                return ResourceManager.GetString("messageBoxNoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reset settings.
        /// </summary>
        internal static string messageBoxResetSettingsButtonOk {
            get {
                return ResourceManager.GetString("messageBoxResetSettingsButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all settings to their default values?.
        /// </summary>
        internal static string messageBoxResetSettingsText {
            get {
                return ResourceManager.GetString("messageBoxResetSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unhandled error occurred. The application will close now.
        ///
        ///Please open a new issue with the content of your log file on
        ///{0}.
        /// </summary>
        internal static string messageBoxUnhandledException {
            get {
                return ResourceManager.GetString("messageBoxUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Manual configuration.
        /// </summary>
        internal static string radioButtonManualProxy {
            get {
                return ResourceManager.GetString("radioButtonManualProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _None.
        /// </summary>
        internal static string radioButtonNoProxy {
            get {
                return ResourceManager.GetString("radioButtonNoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S_ystem.
        /// </summary>
        internal static string radioButtonSystemProxy {
            get {
                return ResourceManager.GetString("radioButtonSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        internal static string saveFileDialogTitle {
            get {
                return ResourceManager.GetString("saveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string Skin_Dark {
            get {
                return ResourceManager.GetString("Skin_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string Skin_Light {
            get {
                return ResourceManager.GetString("Skin_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not modify.
        /// </summary>
        internal static string TagEditAction_DoNotModify {
            get {
                return ResourceManager.GetString("TagEditAction_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear tag.
        /// </summary>
        internal static string TagEditAction_Empty {
            get {
                return ResourceManager.GetString("TagEditAction_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save in tag.
        /// </summary>
        internal static string TagEditAction_Modify {
            get {
                return ResourceManager.GetString("TagEditAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not modify.
        /// </summary>
        internal static string TagRemoveAction_DoNotModify {
            get {
                return ResourceManager.GetString("TagRemoveAction_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear tag.
        /// </summary>
        internal static string TagRemoveAction_Empty {
            get {
                return ResourceManager.GetString("TagRemoveAction_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Releases history.
        /// </summary>
        internal static string textBlockReleasesWebsite {
            get {
                return ResourceManager.GetString("textBlockReleasesWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help translate.
        /// </summary>
        internal static string textBlockTranslationHelp {
            get {
                return ResourceManager.GetString("textBlockTranslationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When downloading a track, if the same file (name) already exists, it will be checked against the track to download.
        ///If the size of both files differ from less than this value (in percent), the track download will be skipped.
        ///Set this value to 0 in order to always download tracks, even if already existing on disk.
        ///
        ///Recommended value = 5.
        /// </summary>
        internal static string textBoxAllowedFileSizeDifference_ToolTip {
            get {
                return ResourceManager.GetString("textBoxAllowedFileSizeDifference_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxCoverArtFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxCoverArtFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum number of tries performed to download a track if it fails.
        ///After that number is reached (for each track), the track download will be skipped.
        ///
        ///Recommended value = 7.
        /// </summary>
        internal static string textBoxDownloadMaxTries_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadMaxTries_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used to control the exponential back-off mechanism.
        ///After each failure of a track download, BandcampDownloader can wait for a specific time before trying again
        ///to download the track in order to avoid tickling the Bandcamp anti-spam filter.
        ///The formula used to compute the time to wait before trying again a download is the following:
        ///time = cooldown * (exponent ^ attempt-count)
        ///
        ///Recommended value = 0.2.
        /// </summary>
        internal static string textBoxDownloadRetryCooldown_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadRetryCooldown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used to control the exponential back-off mechanism.
        ///After each failure of a track download, BandcampDownloader can wait for a specific time before trying again 
        ///to download the track in order to avoid tickling the Bandcamp anti-spam filter.
        ///The formula used to compute the time to wait before trying again a download is the following:
        ///time = cooldown * (exponent ^ attempt-count)
        ///
        ///Recommended value = 4.
        /// </summary>
        internal static string textBoxDownloadRetryExponent_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadRetryExponent_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can use placeholders to customize the download folder depending on the album:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxDownloadsPath_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadsPath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {title} will be replaced by the track name
        ///- {tracknum} will be replaced by the track number
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxPlaylistFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxPlaylistFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste URLs of albums to download here. You can specify multiple URLs by writing one URL per line.
        ///
        ///A Bandcamp URL looks like: http://[artist].bandcamp.com/album/[album] or http://[artist].bandcamp.com/track/[track]
        ///Paste artist pages: http://[artist].bandcamp.com and check &quot;☑ Download artist discography&quot; to download all their albums..
        /// </summary>
        internal static string textBoxUrlsPlaceholder {
            get {
                return ResourceManager.GetString("textBoxUrlsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string windowSettings_Title {
            get {
                return ResourceManager.GetString("windowSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string windowUpdate_Title {
            get {
                return ResourceManager.GetString("windowUpdate_Title", resourceCulture);
            }
        }
    }
}
